apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbac-demo-app
  namespace: production
  labels:
    app: rbac-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rbac-demo-app
  template:
    metadata:
      labels:
        app: rbac-demo-app
    spec:
      imagePullSecrets:
        - name: dockerhub-cred
      containers:
        - name: rbac-demo-app
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 3000
